# Generated by Django 5.2.6 on 2025-09-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='file',
            field=models.FileField(default=1, upload_to='uploads/% Y/% m/% d/'),
            preserve_default=False,
        ),
    ]
