# Generated by Django 5.2.6 on 2025-09-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='file',
        ),
        migrations.AddField(
            model_name='transaction',
            name='upload',
            field=models.FileField(default=1, upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
