# Generated by Django 5.2.6 on 2025-09-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_transaction_file_transaction_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='upload',
            field=models.FileField(upload_to='uploads/%Y-%m-%d'),
        ),
    ]
