# Generated by Django 5.2.6 on 2025-09-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y-%m-%d'),
        ),
    ]
