# Generated by Django 5.2.6 on 2025-09-16 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='upload',
        ),
        migrations.CreateModel(
            name='TransactionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y-%m-%d')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='transactions.transaction')),
            ],
        ),
    ]
