# Generated by Django 5.2.4 on 2025-09-12 04:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_gain', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_transaction', models.PositiveIntegerField(default=0)),
                ('total_category', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Report',
                'verbose_name_plural': 'Monthly Reports',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DayReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_gain', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_transaction', models.PositiveIntegerField(default=0)),
                ('total_category', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Report',
                'verbose_name_plural': 'Daily Reports',
                'ordering': ['-date'],
                'unique_together': {('date', 'user')},
            },
        ),
        migrations.CreateModel(
            name='YearReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_gain', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_transaction', models.PositiveIntegerField(default=0)),
                ('total_category', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yearly Report',
                'verbose_name_plural': 'Yearly Reports',
                'ordering': ['-start_date'],
                'unique_together': {('start_date', 'end_date', 'user')},
            },
        ),
    ]
